# Generated by Django 5.0.1 on 2024-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_staff_notification_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
